# Generated by Django 5.0.1 on 2025-09-22 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('request_number', models.IntegerField(unique=True)),
                ('request_by', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('MWK', 'MWK'), ('USD', 'USD')], max_length=3)),
                ('approver_id', models.UUIDField()),
                ('purpose', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('initiated_on', models.DateTimeField(auto_now_add=True)),
                ('required_on', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-updated_at'],
            },
        ),
    ]
